---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: cibuilds/hugo:0.70
  commands:
  - hugo --minify
  environment:
    HUGO_ENV: production

- name: deploy
  pull: always
  image: lucap/drone-netlify
  settings:
    domain: syfaro.net
    path: ./public
    site_id: 26af9866-53ac-4f16-ab80-5d90bcc03145
  environment:
    NETLIFY_TOKEN:
      from_secret: netlify_token
  when:
    branch:
    - master

...
