baseURL = "https://syfaro.net"
languageCode = "en-us"
title = "Syfaro"
theme = "fox"

enableGitInfo = true
relativeURLs = true

[params]
  description = "Hi. I'm a purple fox."
  umami = "https://u.syfaro.com/umami.js"
  umami_id = "20be2cc7-67be-48f3-8614-64f689910989"

[imaging]
  resampleFilter = "Lanczos"

[taxonomies]
