baseURL = "https://syfaro.net"
languageCode = "en-us"
title = "Syfaro"
theme = "fox"

enableGitInfo = true
relativeURLs = true

[params]
  description = "Hi. I'm a purple fox."
  peppershrike = "https://peppershrike.huefox.com"
  fathom = "//fathom.syfaro.net/tracker.js"
  fathom_id = "DFPYF"

[imaging]
  resampleFilter = "Lanczos"

[taxonomies]
