baseURL = "https://syfaro.net"
languageCode = "en-us"
title = "Syfaro"
theme = "fox"

enableGitInfo = true
relativeURLs = true

[params]
  description = "Hi. I'm a purple fox."
  fathom = "//fathom.huefox.com/tracker.js"
  fathom_id = "OCGRF"

[imaging]
  resampleFilter = "Lanczos"

[taxonomies]
